[project]
authors = ["Robert Cocker <https://robertcocker.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community"]
description = "A framework in Mojo for AI/ML/DL and other domains."
name = "PyMo"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
test = "magic run mojo test test_pymo.mojo && mojo run test/test_libm.mojo && mojo run test/test_libpm.mojo && mojo run test/test_sys.mojo"
format = "magic run mojo format ./"
build = "magic run mojo package pymo -o pymo.mojopkg"

[dependencies]
max = ">=25.1.0,<26"
python = ">=3.12.9,<3.13"
pandas = ">=2.2.3,<3"
numpy = ">=1.26.4,<2"
scikit-learn = ">=1.6.1,<2"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.0,<4"
cpython = ">=3.12.9,<4"
notebook = ">=7.3.2,<8"
python-lsp-server = ">=1.12.2,<2"
pandoc = ">=3.6.3,<4"
pytest = ">=8.3.4,<9"
extramojo = ">=0.9.0,<0.10"
jax = ">=0.4.35,<0.5"
polars = ">=1.22.0,<2"
