[project]
authors = ["rcghpge <rcocker87@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "A framework in Mojo for AI/ML/DL, and other domains."
name = "PyMo"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
test = "magic run mojo test test_pymo.mojo && mojo run test/test_libm.mojo && mojo run test/test_libpm.mojo"
format = "magic run mojo format ./"
build = "magic run mojo package pymo -o pymo.\U0001F4E6"

[dependencies]
max = ">=24.6.0,<25"
python = ">=3.12.8,<3.13"
pandas = ">=2.2.3,<3"
numpy = ">=1.26.4,<2"
scikit-learn = ">=1.6.1,<2"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.0,<4"
cpython = ">=3.12.8,<4"
